name: drl-tf2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2019.11.27
  - cairo=1.14.12
  - certifi=2019.11.28
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - glib=2.63.1
  - graphite2=1.3.13
  - graphviz=2.40.1
  - harfbuzz=1.8.8
  - icu=58.2
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - ncurses=6.1
  - openssl=1.1.1d
  - pango=1.42.4
  - pcre=8.43
  - pip=19.1.1
  - pixman=0.38.0
  - pydot=1.4.1
  - python=3.7.3
  - readline=7.0
  - rope=0.14.0
  - setuptools=41.0.1
  - sqlite=3.28.0
  - tk=8.6.8
  - tqdm=4.40.0
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - astroid==2.3.3
    - atari-py==0.2.6
    - attrs==19.3.0
    - box2d-py==2.3.8
    - cffi==1.12.3
    - chardet==3.0.4
    - cloudpickle==1.2.1
    - cycler==0.10.0
    - cython==0.29.13
    - dill==0.3.1.1
    - future==0.17.1
    - gast==0.2.2
    - glfw==1.8.2
    - google-pasta==0.1.7
    - googleapis-common-protos==1.6.0
    - grpcio==1.22.0
    - gym==0.13.0
    - h5py==2.9.0
    - idna==2.8
    - imageio==2.5.0
    - isort==4.3.21
    - joblib==0.13.2
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - lazy-object-proxy==1.4.2
    - lockfile==0.12.2
    - markdown==3.1.1
    - matplotlib==3.1.1
    - mccabe==0.6.1
    - mujoco-py==2.0.2.5
    - numpy==1.16.4
    - opencv-python==4.1.1.26
    - pandas==0.25.1
    - pillow==6.1.0
    - promise==2.2.1
    - protobuf==3.8.0
    - pycparser==2.19
    - pyglet==1.3.3
    - pylint==2.4.4
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
    - pytz==2019.2
    - requests==2.22.0
    - scipy==1.3.3
    - seaborn==0.9.0
    - six==1.12.0
    - tb-nightly==1.14.0a20190603
    - tensorflow==2.0.0b1
    - tensorflow-datasets==1.3.0
    - tensorflow-metadata==0.15.1
    - termcolor==1.1.0
    - tf-estimator-nightly==1.14.0.dev2019060501
    - typed-ast==1.4.0
    - urllib3==1.25.7
    - werkzeug==0.15.4
    - wrapt==1.11.2
